CREATE TABLE IF NOT EXISTS public.users (
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName varchar(30) NOT NULL,
    lastName varchar(30) NOT NULL
    );

INSERT INTO users (user_id, firstName, lastName)
SELECT 1, 'Pavel', 'Plamenev'
    WHERE
NOT EXISTS (
SELECT user_id FROM users WHERE user_id = 1
);

INSERT INTO users (user_id, firstName, lastName)
SELECT 3, 'Gennagiy', 'Bulkin'
    WHERE
NOT EXISTS (
SELECT user_id FROM users WHERE user_id = 3
);

DELETE FROM users WHERE user_id = 2;