doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/src/InfrastructureLayer/Postgres/migrations'
    enable_profiler: false
    migrations:
        - "App\\InfrastructureLayer\\Postgres\\migrations\\Version20231204145028"
        - "App\\InfrastructureLayer\\Postgres\\migrations\\Version20231226121521"
        - "App\\InfrastructureLayer\\Postgres\\migrations\\Version20231227071852"
        - "App\\InfrastructureLayer\\Postgres\\migrations\\Version20231228110604"
